<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FBCOMPARE" Id="{87c16756-fddf-42f9-a69c-1419ae458759}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FBCOMPARE
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>