<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FBMACHINE" Id="{c975d90d-848c-4dc5-b717-6d92fef38257}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FBMACHINE
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>